-- CODIGO DE "Administrador_Local". Permite crear los usuarios PRY2205_USER1 y PRY2205_USER2, con sus respectivos permisos

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_P;
CREATE USER PRY2205_USER1 IDENTIFIED BY "Duoc.2024" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER PRY2205_USER2 IDENTIFIED BY "Duoc.2024" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

ALTER USER PRY2205_USER1 QUOTA UNLIMITED ON USERS;

GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;

GRANT CREATE SESSION TO PRY2205_USER1;
GRANT CREATE TABLE TO PRY2205_USER1;
GRANT CREATE VIEW TO PRY2205_USER1;
GRANT CREATE INDEX TO PRY2205_USER1;
GRANT CREATE SYNONYM TO PRY2205_USER1;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_USER1;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE INDEX, CREATE SYNONYM, CREATE PUBLIC SYNONYM TO PRY2205_USER1;

GRANT CREATE SESSION, CREATE VIEW TO PRY2205_USER2;

-- CODIGO DE "Conexion_USER1". Todo relacionado al usuario 1, el cual tiene acceso mas completo a las funciones


CREATE OR REPLACE PUBLIC SYNONYM SYN_MEDICO FOR PRY2205_USER1.MEDICO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_CARGO FOR PRY2205_USER1.CARGO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_BONO_CONSULTA FOR PRY2205_USER1.BONO_CONSULTA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PACIENTE FOR PRY2205_USER1.PACIENTE;
CREATE OR REPLACE PUBLIC SYNONYM SYN_SALUD FOR PRY2205_USER1.SALUD;
CREATE OR REPLACE PUBLIC SYNONYM SYN_SISTEMA_SALUD FOR PRY2205_USER1.SISTEMA_SALUD;


GRANT SELECT ON PRY2205_USER1.MEDICO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.CARGO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.BONO_CONSULTA TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PACIENTE TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.SALUD TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.SISTEMA_SALUD TO PRY2205_ROL_P;


CREATE INDEX IDX_MEDICO_CAR_ID ON PRY2205_USER1.MEDICO(car_id);


CREATE OR REPLACE VIEW VW_AUM_MEDICO_X_CARGO AS
SELECT
    TO_CHAR(m.rut_med, 'FM09G999G999') || '-' || m.dv_run AS RUT_MEDICO,
    c.nombre AS CARGO,
    m.sueldo_base AS SUELDO_ACTUAL,
    ROUND(m.sueldo_base * 1.15) AS SUELDO_AUMENTADO
FROM
    SYN_MEDICO m
JOIN
    SYN_CARGO c ON m.car_id = c.car_id
WHERE
    LOWER(c.nombre) LIKE '%atención%' OR LOWER(c.nombre) LIKE '%atencion%'
ORDER BY
    ROUND(m.sueldo_base * 1.15) DESC;
    
GRANT SELECT ON PRY2205_USER1.BONO_CONSULTA TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.PACIENTE TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.SALUD TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.SISTEMA_SALUD TO PRY2205_USER2;

-- CODIGO DE "Conexion_USER2". Todo relacionado al usuario 2, el cual tiene permisos mas restringidos

CREATE OR REPLACE VIEW VW_RECALCULO_COSTOS AS
SELECT
    TO_CHAR(p.pac_run, 'FM99G999G999') || '-' || p.dv_run AS RUT_PACIENTE,
    p.apaterno || ' ' || p.amaterno || ' ' || p.pnombre AS NOMBRE_PACIENTE,
    s.descripcion AS SISTEMA_SALUD,
    '$' || TO_CHAR(bc.costo, 'FM999G999') AS COSTO,
    bc.hr_consulta AS HORARIO_ATENCION,
    TO_CHAR(bc.fecha_bono, 'MM-YYYY') AS FECHA_CONSULTA,
    '$' || TO_CHAR(
        CASE
            WHEN bc.costo BETWEEN 15000 AND 25000 THEN ROUND(bc.costo * 1.15)
            WHEN bc.costo > 25000 THEN ROUND(bc.costo * 1.20)
            ELSE bc.costo
        END, 'FM999G999'
    ) AS REAJUSTE
FROM
    SYN_BONO_CONSULTA bc
JOIN
    SYN_PACIENTE p ON bc.pac_run = p.pac_run
JOIN
    SYN_SALUD s ON p.sal_id = s.sal_id
WHERE
    EXTRACT(YEAR FROM bc.fecha_bono) = EXTRACT(YEAR FROM SYSDATE) - 1
    AND bc.hr_consulta > '17:15'
    AND p.sal_id IN (
        SELECT sa.sal_id
        FROM SYN_SALUD sa
        JOIN SYN_SISTEMA_SALUD ss ON sa.tipo_sal_id = ss.tipo_sal_id
        WHERE UPPER(ss.descripcion) LIKE '%ISAPRE%' 
           OR UPPER(ss.descripcion) LIKE '%FONASA%'
    )
ORDER BY
    bc.fecha_bono ASC,
    p.pac_run ASC
WITH READ ONLY;