CREATE TABLE RECAUDACION_BONOS_MEDICOS AS
SELECT 
    TO_CHAR(MEDICO.rut_med, 'fm09G999G999') || '-' || MEDICO.dv_run AS "RUT_MÉDICO", 
    UPPER(MEDICO.pnombre || ' ' || MEDICO.apaterno || ' ' || MEDICO.amaterno) AS "NOMBRE MÉDICO", 
    TO_CHAR(SUM(BONO_CONSULTA.costo), '$999G999G999') AS "TOTAL_RECAUDADO", 
    INITCAP(UNIDAD_CONSULTA.nombre) AS "UNIDAD_MEDICA"
FROM BONO_CONSULTA 
JOIN MEDICO ON BONO_CONSULTA.rut_med = MEDICO.rut_med
JOIN UNIDAD_CONSULTA ON MEDICO.uni_id = UNIDAD_CONSULTA.uni_id
WHERE MEDICO.car_id NOT IN (100, 500, 600)
  AND EXTRACT(YEAR FROM BONO_CONSULTA.fecha_bono) = EXTRACT(YEAR FROM SYSDATE) - 1
GROUP BY 
    MEDICO.rut_med,
    MEDICO.dv_run,
    MEDICO.pnombre,
    MEDICO.apaterno,
    MEDICO.amaterno,
    UNIDAD_CONSULTA.nombre
ORDER BY SUM(BONO_CONSULTA.costo) ASC;
SELECT * FROM RECAUDACION_BONOS_MEDICOS;    


SELECT 
    UPPER(ESPECIALIDAD_MEDICA.nombre) AS "ESPECIALIDAD",
    COUNT(BONO_CONSULTA.id_bono) AS "TOTAL BONOS",
    TO_CHAR(SUM(BONO_CONSULTA.costo), 'fm$999G999G999') AS "PERDIDA TOTAL"
FROM BONO_CONSULTA
JOIN ESPECIALIDAD_MEDICA ON BONO_CONSULTA.esp_id = ESPECIALIDAD_MEDICA.esp_id
WHERE BONO_CONSULTA.id_bono IN (
    SELECT id_bono FROM BONO_CONSULTA 
    MINUS 
    SELECT id_bono FROM PAGOS
)
GROUP BY 
    UPPER(ESPECIALIDAD_MEDICA.nombre)
ORDER BY 
    COUNT(BONO_CONSULTA.id_bono) ASC, 
    SUM(BONO_CONSULTA.costo) DESC;




    
     