ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- PRY2205_EFT
CREATE USER PRY2205_EFT 
IDENTIFIED BY "MartinJENKINS2501"
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;

-- PRY2205_EFT_DES
CREATE USER PRY2205_EFT_DES 
IDENTIFIED BY "MartinJENKINS2502"
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;

-- PRY2205_EFT_CON
CREATE USER PRY2205_EFT_CON 
IDENTIFIED BY "MartinJENKINS2503"
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;


GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;


GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE SYNONYM, CREATE PUBLIC SYNONYM TO PRY2205_EFT;
GRANT CREATE SEQUENCE, CREATE PROCEDURE, CREATE VIEW TO PRY2205_EFT_DES;
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_C;

GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;